import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import HomePage from "../components/HomePage";
import Nav from "../components/Nav";

export default function Home({ data }) {
  const [count, setCount] = useState(0);
  return (
    <div>
      <Head>
        <title>Done with it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav count={count}></Nav>
      <HomePage count={count} setCount={setCount} data={data} />
    </div>
  );
}
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://fakestoreapi.com/products`);
  const data = await res.json();
  // console.log(data);
  // Pass data to the page via props
  return { props: { data } };
}
